name       : kwayland-integration
version    : 5.10.5
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.5/kwayland-integration-5.10.5.tar.xz : be55e85c78635a075946be5fc14ea2dddf7a5b9d0e9911bd2a85d82777863e68
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
