name       : kwayland-integration
version    : 5.20.5
release    : 59
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.5/kwayland-integration-5.20.5.tar.xz : 33f364670a1c19b84fe1bda40e543ebcc9e7593e932a7d18b9815f150ac21f67
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - kguiaddons-devel
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
