name       : kwayland-integration
version    : 5.12.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.3/kwayland-integration-5.12.3.tar.xz : b1f59e9b29c69b4cc711323e990a86ff0a84efa4f5b03545752573a29b6da133
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
