name       : kwayland-integration
version    : 5.16.1
release    : 34
source     :
    - https://download.kde.org/stable/plasma/5.16.1/kwayland-integration-5.16.1.tar.xz : a519924e719d08a7ed81a84f18650cac0c46d2866e825ca8d102582fad9e6bd1
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
