name       : kwayland-integration
version    : 5.11.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.3/kwayland-integration-5.11.3.tar.xz : cefcc75a967228469bb72dd763655c94cc59ce067e01c0eff1fda25c30fcac48
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
