name       : kwayland-integration
version    : 5.16.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.0/kwayland-integration-5.16.0.tar.xz : 3f3e53ef60d0f8725095278c247df7b2f1b02bb6a082327042e0cb5d997233c6
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
