name       : kwayland-integration
version    : 5.17.4
release    : 42
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.4/kwayland-integration-5.17.4.tar.xz : 3c6b14bcf7f6f3a927d485afba9ed3051cbe513441ed17f5d484419388da825c
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kguiaddons-devel
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
