name       : kwayland-integration
version    : 5.18.1
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.1/kwayland-integration-5.18.1.tar.xz : e9d582560becb11b2884df642dbb0796696a2d94d55e92e1d87db8d312f443a3
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kguiaddons-devel
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
