name       : kwayland-integration
version    : 5.12.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.2/kwayland-integration-5.12.2.tar.xz : d6a650cc89f1ac92aec36f666149d0593972b5fb258d342bbd561c8db66e9be8
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
