name       : kwayland-integration
version    : 5.21.3
release    : 62
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.3/kwayland-integration-5.21.3.tar.xz : 0c7641e27a38094077a204ca10c410b2f4f92c0a077b32a22bb5d5ae572b1c4f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - kguiaddons-devel
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
