name       : kwayland-integration
version    : 5.18.5
release    : 48
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.5/kwayland-integration-5.18.5.tar.xz : 82d6943d79a9a2a9bce10623adb2c9af396a2dcf258a723bb349aafbde20e6d5
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kguiaddons-devel
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
