name       : kwayland-integration
version    : 5.11.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/kwayland-integration-5.11.1.tar.xz : 70ae95bb9ccc43ca407ec3fc55dca6de20e0ff9d7e48583444c238b6fe6634c0
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
