name       : kwayland-integration
version    : 5.13.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.0/kwayland-integration-5.13.0.tar.xz : ee43888f2c874dbaac5d4ac6f8b5f8b352ae5209ae4da8bf64de10e213879e43
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
