name       : kwayland-integration
version    : 5.12.5
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.5/kwayland-integration-5.12.5.tar.xz : e363bdcc70ff0a93b1350980ac6f638fcf73224a6f4b1c75bb3058c13dd60c17
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
