name       : kwayland-integration
version    : 5.13.3
release    : 19
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.3/kwayland-integration-5.13.3.tar.xz : df6903caa379a3d6634f2697cd4217c0e032f6f8630dab0320ec4746fb1b5cee
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
