name       : kwayland-integration
version    : 5.11.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.2/kwayland-integration-5.11.2.tar.xz : 5566cad72995326925b1ef0c49c0c3920bdac15a321f553e826634344c72f4b7
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
