name       : kwayland-integration
version    : 5.10.1
release    : 2
source     :
    - https://download.kde.org/stable/plasma/5.10.1/kwayland-integration-5.10.1.tar.xz : 86256419e7fbfe95830d565bd8f1d203ffea59c8d59f5d8806fd56f3b59fc426
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
