name       : kwayland-integration
version    : 5.19.5
release    : 53
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.5/kwayland-integration-5.19.5.tar.xz : 6d1bed734cd256604736417846f891abad9bd7c2a45527fc6fc10560322c8a14
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kguiaddons-devel
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
