name       : kwayland-integration
version    : 5.11.0
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.11.0/kwayland-integration-5.11.0.tar.xz : c218e8f58bbac918419ddb932907eacb361a468e45ad5f283af488aa27770fef
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
