name       : kwayland-integration
version    : 5.13.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.1/kwayland-integration-5.13.1.tar.xz : c44fc7aff98028e3437a666be87d419933df828b6096fed3cd9b79f01e016d10
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
