name       : kwayland-integration
version    : 5.13.5
release    : 21
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.5/kwayland-integration-5.13.5.tar.xz : ba796c6284613beee8445f6ed574d3f8ea6ab6bf08d5d9ec2bdf8c5691ce13e2
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
