name       : kwayland-integration
version    : 5.16.5
release    : 38
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.5/kwayland-integration-5.16.5.tar.xz : 63724ecfb6db053ee949273979b393192309dbeed45b59bc193a605f90232282
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
