name       : kwayland-integration
version    : 5.9.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.9.5/kwayland-integration-5.9.5.tar.xz : f9700c4f796b0c311c2eecd1354b5f32adc1028e5a4ccacc6edad7dd0c3e8a1e
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
