name       : kwayland-integration
version    : 5.20.4
release    : 57
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.4/kwayland-integration-5.20.4.tar.xz : 2dd985dd8d21cdc7743b9f297d0d582f960339b4714953564f2f047d28cee53d
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kguiaddons-devel
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
