name       : kwayland-integration
version    : 5.11.5
release    : 9
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.5/kwayland-integration-5.11.5.tar.xz : fae66ee78655770f1c40444899398316b7509481b38d5df7b3ab425afd7f3a76
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
