name       : kwayland-integration
version    : 5.14.5
release    : 28
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.5/kwayland-integration-5.14.5.tar.xz : 7400869e31eb397d626d5857dffe91542010721ef0818e62da3dc65116eca065
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
