name       : kwayland-integration
version    : 5.14.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.0/kwayland-integration-5.14.0.tar.xz : 812f8621c7bc1ab5df37937c50af172a3a86530f6f3589347abe4353cfc2aba7
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
