name       : kwayland-integration
version    : 5.13.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.2/kwayland-integration-5.13.2.tar.xz : 3ab8d8bbfbbb7d210dccea4d1b6b21b019293b43d940da72ed3508878e291d2e
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
