name       : kwayland-integration
version    : 5.27.7
release    : 88
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/kwayland-integration-5.27.7.tar.xz : 1e7997688a329563f62ce7534e82326a4317d9ecf12403d12e70d4d237316ebb
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
