name       : kwayland-integration
version    : 5.13.4
release    : 20
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.4/kwayland-integration-5.13.4.tar.xz : 01a6d19f8ec7ccb4e2fe63789359bbeeb9232c51e3973d5a2a8f977d7f8b1a56
license    : LGPL-2.1
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kidletime-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
